server:
  port: 8080

spring:
  application:
    name: api-gateway

spring:
  cloud:
    gateway:
      routes:
        - id: kitchen
          uri: http://kitchen:8001
          predicates:
            - Path=/kitchen/**

        - id: delivery
          uri: http://delivery:8002
          predicates:
            - Path=/delivery/**