global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "kitchen"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["kitchen:8001"]

  - job_name: "delivery"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["delivery:8002"]

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:8080"]